### ISSUE TITLE
Doesn’t work with Portable Mode

### ISSUE THREAD

**Issue by rsgranne** [3axap4eHko/file-templates-manager#2]
The June 2018 version of VSCode supports Portable Mode (see <https://code.visualstudio.com/updates/v1_25>. According to the documentation for Portable Mode at <https://code.visualstudio.com/docs/editor/portable#_enable-portable-mode>:

> After unzipping the VS Code download, simply create a `data` folder within Code's folder…
> 
> From then on, that folder will be used to contain all Code data, including session state, preferences, extensions, etc.

The problem is that File Templates Manager stores its templates at `%HOME%\AppData\Roaming\Code\User\CodeTemplates\`, which makes it impossible to use with Portable Mode.

I teach college courses & some of my students don’t have laptops, which means they have to use VSCode in Portable Mode. One of the key extensions we use is File Templates Manager, but it’s inability to work with Portable Mode is a big problem.

**Comment by 3axap4eHko** [comment]
@rsgranne I hope commit 957ed0b04fdf4cdbff10e1d61f466b931bdebb62 should resolve the issue, could you confirm?
